import type { CanvasData, CustomTheme, HeatmapMode, ThemeId } from './types';
const key=(id:string)=>`synapse:v1:canvas:${id}`;
export function loadCanvas(id:string):CanvasData|null { try { const raw=localStorage.getItem(key(id)); if(!raw)return null; const data=JSON.parse(raw); if(!data||typeof data.nodes!=='object'||!data.viewport) throw Error('Invalid canvas shape'); return {...data,viewport:{x:Number(data.viewport.x)||0,y:Number(data.viewport.y)||0,zoom:Number(data.viewport.zoom)||1}}; } catch { return null; } }
export function saveCanvas(canvas:CanvasData){ try { localStorage.setItem(key(canvas.id),JSON.stringify(canvas)); return true; } catch { return false; } }
const UI_SETTINGS_KEY='synapse:v1:ui-settings';
const CUSTOM_THEMES_KEY='synapse:v1:custom-themes';
const HEATMAP_MODES:HeatmapMode[]=['full','mini','hidden'];
export function loadUISettings():{heatmapMode:HeatmapMode;theme:ThemeId} { try { const raw=localStorage.getItem(UI_SETTINGS_KEY); if(!raw)return {heatmapMode:'full',theme:'light'}; const data=JSON.parse(raw); if(!data||typeof data!=='object') return {heatmapMode:'full',theme:'light'}; return {heatmapMode:HEATMAP_MODES.includes(data.heatmapMode)?data.heatmapMode as HeatmapMode:'full',theme:typeof data.theme==='string'&&data.theme?data.theme:'light'}; } catch { return {heatmapMode:'full',theme:'light'}; } }
export function saveUISettings(settings:{heatmapMode:HeatmapMode;theme:ThemeId}):void { try { localStorage.setItem(UI_SETTINGS_KEY,JSON.stringify(settings)); } catch { /* ignore quota / privacy-mode errors */ } }
export function loadCustomThemes():Record<ThemeId,CustomTheme> { try { const raw=localStorage.getItem(CUSTOM_THEMES_KEY); if(!raw)return {}; const data=JSON.parse(raw); if(!data||typeof data!=='object'||Array.isArray(data))return {}; const themes:Record<ThemeId,CustomTheme>={}; for(const [id,theme] of Object.entries(data)){const candidate=theme as Partial<CustomTheme>;if(candidate&&typeof candidate==='object'&&typeof candidate.id==='string'&&typeof candidate.name==='string'&&(candidate.base==='light'||candidate.base==='dark')&&candidate.colors&&typeof candidate.colors==='object'&&!Array.isArray(candidate.colors)&&typeof candidate.createdAt==='number'&&typeof candidate.updatedAt==='number')themes[id]=candidate as CustomTheme;} return themes; } catch { return {}; } }
export function saveCustomThemes(map:Record<ThemeId,CustomTheme>):void { try { localStorage.setItem(CUSTOM_THEMES_KEY,JSON.stringify(map)); } catch { /* ignore quota / privacy-mode errors */ } }
