'use client';
import {create} from 'zustand';
import {loadCanvas,loadCustomThemes,loadUISettings,saveCanvas,saveCustomThemes,saveUISettings} from './persistence';
import {applyTheme} from './theme';
import {children,descendants,roots} from './operations/hierarchy';
import {makeNode} from './operations/nodes';
import {HORIZONTAL_INDENT,NODE_MIN_HEIGHT,NODE_WIDTH,STATUS_ORDER,type CanvasData,type CustomTheme,type HeatmapMode,type Position,type ThemeId} from './types';

type State={canvas:CanvasData|null;editingId:string|null;justCreatedId:string|null;saved:boolean;heatmapMode:HeatmapMode;theme:ThemeId;customThemes:Record<ThemeId,CustomTheme>;init:(id:string,size:Position)=>void;update:(fn:(c:CanvasData)=>void)=>void;createRoot:(size:Position)=>void;createChild:(id:string)=>void;remove:(id:string)=>void;setEditing:(id:string|null)=>void;flashSaved:()=>void;setHeatmapMode:(mode:HeatmapMode)=>void;setTheme:(themeId:ThemeId)=>void;createCustomTheme:(name:string,base:'light'|'dark',colors:Record<string,string>)=>ThemeId;updateCustomTheme:(id:ThemeId,updates:Partial<Pick<CustomTheme,'name'|'base'|'colors'>>)=>void;deleteCustomTheme:(id:ThemeId)=>void};
const initialSettings=typeof window==='undefined'?{heatmapMode:'full' as HeatmapMode,theme:'light' as ThemeId}:loadUISettings();
const initialCustomThemes=typeof window==='undefined'?{} as Record<ThemeId,CustomTheme>:loadCustomThemes();
let timer:ReturnType<typeof setTimeout>|undefined,flash:ReturnType<typeof setTimeout>|undefined;
function seed(id:string):CanvasData {const t=Date.now();let seq=0;const c:CanvasData={id,name:'My Canvas',nodes:{},viewport:{x:0,y:0,zoom:1},createdAt:t,updatedAt:t};const add=(parentId:string|null,content:string,status:any='none',isCollapsed=false)=>{const nid=crypto.randomUUID();const p=parentId?c.nodes[parentId].position:{x:80,y:160};const siblings=parentId?children(c,parentId):[];c.nodes[nid]={...makeNode(nid,content,parentId,parentId?{x:p.x+HORIZONTAL_INDENT,y:siblings.length?Math.max(...siblings.map(s=>s.position.y))+NODE_MIN_HEIGHT+30:p.y}:p),status,isCollapsed,createdAt:t+seq++};return nid};const root=add(null,'Eclampsia — Management Framework');const def=add(root,'Definition & Pathophysiology','mastered',true);add(def,'New-onset seizures in a pre-eclamptic patient');add(def,'Endothelial dysfunction, vasospasm & hyperperfusion');const red=add(root,'Red Flag Symptoms');['Severe frontal headache','Visual disturbances — scotoma, blurring','Epigastric / right upper quadrant pain','Hyperreflexia with clonus'].forEach(x=>add(red,x));const mgmt=add(root,'Acute Management');const mg=add(mgmt,'MgSO₄ Protocol','none',true);add(mg,'Loading dose: 4 g IV over 15–20 min','mastered');add(mg,'Maintenance: 1 g/hour infusion for 24 h','review');add(mg,'Toxicity watch: reflexes, RR, urine output','failed');add(mg,'Antidote: Calcium gluconate 1 g IV','failed');add(mgmt,'Delivery planning — definitive treatment','failed');add(mgmt,'BP control: Labetalol / Hydralazine','review');const diff=add(root,'Differential Diagnosis','mastered',true);['Epilepsy','Meningitis / encephalitis','Hypoglycemia'].forEach(x=>add(diff,x));return c;}
export const useCanvasStore=create<State>((set,get)=>({canvas:null,editingId:null,justCreatedId:null,saved:false,heatmapMode:initialSettings.heatmapMode,theme:initialSettings.theme,customThemes:initialCustomThemes,setHeatmapMode:(mode)=>{set({heatmapMode:mode});saveUISettings({heatmapMode:mode,theme:get().theme})},setTheme:(themeId)=>{set({theme:themeId});saveUISettings({heatmapMode:get().heatmapMode,theme:themeId});applyTheme(themeId,get().customThemes)},createCustomTheme:(name,base,colors)=>{const now=Date.now(),id=`custom-${now}-${Math.random().toString(36).slice(2,8)}`,theme:CustomTheme={id,name,base,colors,createdAt:now,updatedAt:now},customThemes={...get().customThemes,[id]:theme};set({customThemes});saveCustomThemes(customThemes);return id},updateCustomTheme:(id,updates)=>{const existing=get().customThemes[id];if(!existing)return;const customThemes={...get().customThemes,[id]:{...existing,...updates,updatedAt:Date.now()}};set({customThemes});saveCustomThemes(customThemes);if(get().theme===id)applyTheme(id,customThemes)},deleteCustomTheme:(id)=>{if(!get().customThemes[id])return;const customThemes={...get().customThemes};delete customThemes[id];set({customThemes});saveCustomThemes(customThemes);if(get().theme===id)get().setTheme('light')},init:(id,size)=>{let c=loadCanvas(id)||seed(id);if(!loadCanvas(id)){const ns=Object.values(c.nodes);const minX=Math.min(...ns.map(n=>n.position.x)),minY=Math.min(...ns.map(n=>n.position.y)),maxX=Math.max(...ns.map(n=>n.position.x+NODE_WIDTH)),maxY=Math.max(...ns.map(n=>n.position.y+NODE_MIN_HEIGHT));const z=Math.min((size.x-110)/(maxX-minX),(size.y-110)/(maxY-minY),1);c.viewport={zoom:z,x:(size.x-(maxX-minX)*z)/2-minX*z,y:(size.y-(maxY-minY)*z)/2-minY*z};saveCanvas(c)}set({canvas:c})},update:(fn)=>set(s=>{if(!s.canvas)return s;const c=structuredClone(s.canvas);fn(c);c.updatedAt=Date.now();clearTimeout(timer);timer=setTimeout(()=>{saveCanvas(c);get().flashSaved()},400);return {canvas:c}}),createRoot:(size)=>{const c=get().canvas;if(!c)return;const id=crypto.randomUUID(),r=roots(c).length*46,p={x:(size.x/2-c.viewport.x)/c.viewport.zoom-NODE_WIDTH/2+r,y:(size.y/2-c.viewport.y)/c.viewport.zoom-NODE_MIN_HEIGHT/2+r*.6};get().update(x=>{x.nodes[id]=makeNode(id,'',null,p)});set({editingId:id,justCreatedId:id});setTimeout(()=>set({justCreatedId:null}),650)},createChild:(parentId)=>{const c=get().canvas;if(!c)return;const p=c.nodes[parentId],kids=children(c,parentId),id=crypto.randomUUID(),pos={x:p.position.x+HORIZONTAL_INDENT,y:kids.length?Math.max(...kids.map(n=>n.position.y))+NODE_MIN_HEIGHT+30:p.position.y};get().update(x=>{x.nodes[id]=makeNode(id,'',parentId,pos);x.nodes[parentId].isCollapsed=false});set({editingId:id,justCreatedId:id});setTimeout(()=>set({justCreatedId:null}),650)},remove:(id)=>get().update(c=>[id,...descendants(c,id)].forEach(x=>delete c.nodes[x])),setEditing:(editingId)=>set({editingId}),flashSaved:()=>{set({saved:true});clearTimeout(flash);flash=setTimeout(()=>set({saved:false}),1600)}}));
if(typeof window!=='undefined')applyTheme(initialSettings.theme,initialCustomThemes);
