'use client';
import {useEffect,useRef,useState} from 'react';
import {useCanvasStore} from '@/lib/store';
import {children,visibleOrder} from '@/lib/operations/hierarchy';
import {MAX_ZOOM,MIN_ZOOM,NODE_MIN_HEIGHT,NODE_WIDTH,STATUS_META,type Status} from '@/lib/types';
import Node from './Node';
import Toolbar from './Toolbar';

export default function Canvas({canvasId}:{canvasId:string}) {
 const canvas=useCanvasStore(s=>s.canvas), init=useCanvasStore(s=>s.init), update=useCanvasStore(s=>s.update), createRoot=useCanvasStore(s=>s.createRoot), saved=useCanvasStore(s=>s.saved);
 const ref=useRef<HTMLDivElement>(null); const [drag,setDrag]=useState<{id:string;sx:number;sy:number;ox:number;oy:number}|null>(null); const [pan,setPan]=useState<{sx:number;sy:number;ox:number;oy:number}|null>(null);
 useEffect(()=>{init(canvasId,{x:window.innerWidth,y:window.innerHeight})},[canvasId,init]);
 if(!canvas)return <div id="viewport" ref={ref}/>;
 const order=visibleOrder(canvas), counts:Record<Status,number>={none:0,failed:0,review:0,mastered:0}; Object.values(canvas.nodes).forEach(n=>counts[n.status]++);
 const changeZoom=(target:number,mx=(ref.current?.clientWidth||0)/2,my=(ref.current?.clientHeight||0)/2)=>update(c=>{const z=Math.max(MIN_ZOOM,Math.min(MAX_ZOOM,target)), old=c.viewport.zoom, wx=(mx-c.viewport.x)/old,wy=(my-c.viewport.y)/old;c.viewport={x:mx-wx*z,y:my-wy*z,zoom:z}});
 const fit=()=>update(c=>{const ns=Object.values(c.nodes);if(!ns.length){c.viewport={x:0,y:0,zoom:1};return}const minX=Math.min(...ns.map(n=>n.position.x)),minY=Math.min(...ns.map(n=>n.position.y)),maxX=Math.max(...ns.map(n=>n.position.x+NODE_WIDTH)),maxY=Math.max(...ns.map(n=>n.position.y+NODE_MIN_HEIGHT)), w=ref.current!.clientWidth,h=ref.current!.clientHeight,z=Math.max(MIN_ZOOM,Math.min((w-110)/(maxX-minX),(h-110)/(maxY-minY),1));c.viewport={zoom:z,x:(w-(maxX-minX)*z)/2-minX*z,y:(h-(maxY-minY)*z)/2-minY*z}});
 return <><div id="viewport" ref={ref} className={pan?'panning':''} onPointerDown={e=>{if((e.target as Element).closest('.node-card'))return;setPan({sx:e.clientX,sy:e.clientY,ox:canvas.viewport.x,oy:canvas.viewport.y})}} onPointerMove={e=>{if(drag){update(c=>c.nodes[drag.id].position={x:drag.ox+(e.clientX-drag.sx)/canvas.viewport.zoom,y:drag.oy+(e.clientY-drag.sy)/canvas.viewport.zoom})}else if(pan)update(c=>{c.viewport.x=pan.ox+e.clientX-pan.sx;c.viewport.y=pan.oy+e.clientY-pan.sy})}} onPointerUp={()=>{setPan(null);setDrag(null)}} onWheel={e=>{e.preventDefault();const r=ref.current!.getBoundingClientRect();changeZoom(canvas.viewport.zoom*Math.exp(-e.deltaY*(e.ctrlKey?.008:.0018)),e.clientX-r.left,e.clientY-r.top)}}><div id="world" style={{transform:`translate(${canvas.viewport.x}px, ${canvas.viewport.y}px) scale(${canvas.viewport.zoom})`}}><svg id="edges">{order.map(id=>{const n=canvas.nodes[id];if(!n.parentId||!order.includes(n.parentId))return null;const p=canvas.nodes[n.parentId],x1=p.position.x+NODE_WIDTH,y1=p.position.y+NODE_MIN_HEIGHT/2,x2=n.position.x,y2=n.position.y+NODE_MIN_HEIGHT/2,m=x1+Math.max((x2-x1)/2,24);return <path key={id} d={`M ${x1} ${y1} C ${m} ${y1}, ${m} ${y2}, ${x2} ${y2}`} stroke={n.status==='none'?'#c3cad6':STATUS_META[n.status].color}/>})}</svg><div id="nodes">{order.map(id=><Node key={id} node={canvas.nodes[id]} onDrag={(e,id)=>{e.preventDefault();e.stopPropagation();const n=canvas.nodes[id];setDrag({id,sx:e.clientX,sy:e.clientY,ox:n.position.x,oy:n.position.y})}}/>)}</div></div></div>
 <Toolbar onAdd={()=>createRoot({x:ref.current!.clientWidth,y:ref.current!.clientHeight})} onCollapse={()=>update(c=>Object.values(c.nodes).forEach(n=>{if(children(c,n.id).length)n.isCollapsed=true}))} onExpand={()=>update(c=>Object.values(c.nodes).forEach(n=>n.isCollapsed=false))}/>
 <div id="viewbar" className="ui-float"><button className="zb-btn" onClick={()=>changeZoom(canvas.viewport.zoom/1.2)}>−</button><button className="zb-btn" id="zoom-label" onClick={()=>changeZoom(1)}>{Math.round(canvas.viewport.zoom*100)}%</button><button className="zb-btn" onClick={()=>changeZoom(canvas.viewport.zoom*1.2)}>＋</button><div className="zb-sep"/><button className="zb-btn" onClick={fit}>⊡</button><div className="zb-sep"/><div id="save-ind" className={saved?'show':''}><span className="dot"/>Saved</div></div>
 <aside id="legend" className="ui-float"><h4>Knowledge heatmap</h4>{(['failed','review','mastered','none'] as Status[]).map(k=><div className="legend-row" key={k}><span className="sw" style={{background:STATUS_META[k].color}}/><span className="k">{STATUS_META[k].label}{k==='failed'?' — restudy':''}</span><span className="v">{counts[k]}</span></div>)}<div id="health-wrap"><div id="health-bar">{(['mastered','review','failed'] as Status[]).map(k=><i key={k} style={{background:STATUS_META[k].color,width:`${order.length?counts[k]/order.length*100:0}%`}}/>)}</div><div id="health-caption">{order.length?`${counts.mastered} of ${order.length} nodes mastered · ${counts.failed+counts.review} to revisit`:'No nodes yet — create your first topic.'}</div></div></aside>
 <div id="hint" className="ui-float"><span><b>Click text</b> to edit</span><span><b>Drag ⣿</b> to move</span><span><b>Click ●</b> to tag</span><span><b>Scroll</b> to zoom</span><span><b>Drag canvas</b> to pan</span></div></>;
}
