'use client';
import {useCanvasStore} from '@/lib/store';
import {visibleOrder} from '@/lib/operations/hierarchy';
import {STATUS_META,type Status} from '@/lib/types';

export default function HeatmapPanel() {
 const canvas=useCanvasStore(s=>s.canvas), heatmapMode=useCanvasStore(s=>s.heatmapMode), setHeatmapMode=useCanvasStore(s=>s.setHeatmapMode);
 if(!canvas)return null;
 const order=visibleOrder(canvas), counts:Record<Status,number>={none:0,failed:0,review:0,mastered:0}; Object.values(canvas.nodes).forEach(n=>counts[n.status]++);
 if(heatmapMode==='mini')return <div className="heatmap-mini ui-float" role="button" tabIndex={0} aria-label="Expand heatmap" title="Expand heatmap" onClick={e=>{e.stopPropagation();setHeatmapMode('full')}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setHeatmapMode('full')}}} onPointerDown={e=>e.stopPropagation()}>{(['failed','review','mastered','none'] as Status[]).map(k=><span className="heatmap-mini-pair" key={k}><span className="heatmap-mini-dot" style={{background:STATUS_META[k].color}}/><span className="heatmap-mini-count">{counts[k]}</span></span>)}<button className="heatmap-icon-btn" aria-label="Hide heatmap" title="Hide heatmap" onClick={e=>{e.stopPropagation();setHeatmapMode('hidden')}} onPointerDown={e=>e.stopPropagation()}>×</button></div>;
 if(heatmapMode==='hidden')return <button className="heatmap-restore ui-float" aria-label="Show heatmap" title="Show heatmap" onClick={e=>{e.stopPropagation();setHeatmapMode('mini')}} onPointerDown={e=>e.stopPropagation()}><svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true"><rect x="2" y="9" width="3" height="5" rx="1" fill="currentColor"/><rect x="6.5" y="5" width="3" height="9" rx="1" fill="currentColor"/><rect x="11" y="2" width="3" height="12" rx="1" fill="currentColor"/></svg></button>;
 if(heatmapMode!=='full')return null;
 return <aside id="legend" className="ui-float"><div className="heatmap-header"><h4>Knowledge heatmap</h4><div className="heatmap-header-actions"><button className="heatmap-icon-btn" aria-label="Minimize heatmap" title="Minimize heatmap" onClick={e=>{e.stopPropagation();setHeatmapMode('mini')}} onPointerDown={e=>e.stopPropagation()}>–</button><button className="heatmap-icon-btn" aria-label="Hide heatmap" title="Hide heatmap" onClick={e=>{e.stopPropagation();setHeatmapMode('hidden')}} onPointerDown={e=>e.stopPropagation()}>×</button></div></div>{(['failed','review','mastered','none'] as Status[]).map(k=><div className="legend-row" key={k}><span className="sw" style={{background:STATUS_META[k].color}}/><span className="k">{STATUS_META[k].label}{k==='failed'?' — restudy':''}</span><span className="v">{counts[k]}</span></div>)}<div id="health-wrap"><div id="health-bar">{(['mastered','review','failed'] as Status[]).map(k=><i key={k} style={{background:STATUS_META[k].color,width:`${order.length?counts[k]/order.length*100:0}%`}}/>)}</div><div id="health-caption">{order.length?`${counts.mastered} of ${order.length} nodes mastered · ${counts.failed+counts.review} to revisit`:'No nodes yet — create your first topic.'}</div></div></aside>;
}
